### ISSUE TITLE
Ephemeral messages produce 100% one core CPU usage

### ISSUE THREAD

**Issue by TiGR** [wireapp/wire-desktop#1650]
Wire version: 3.2.2840
Wire for web version: 2018.07.26.0854
Operating system: Kubuntu 16.04 LTS, fully updated.

What steps will reproduce the problem?

1. Open some chat, for instance with Otto the Bot.
2. Write some ephemeral message (lasting 30s, for instance).
3. Watch CPU usage spike to 100% of single core.
4. Wait till message disappears and see CPU usage drop to zero.

This is true for both short-lived and long-lived messages (that should not have any animation whatsoever, only indicator changing once in few hours or days).

So, if you have an ephemeral message with a week lifespan in some chat, then you'll have 100% cpu usage anytime within that week that you open that chat.

**Comment by TiGR** [comment]
Just have tested - this is true for web version also.

**Comment by gregor** [comment]
@TiGR Thanks for the report. We decreased the load created by ephemeral messages significantly in https://github.com/wireapp/wire-webapp/pull/4149. This will go live as part of our next public webapp release. Please check at that point.

**Comment by kuetemeier** [comment]
Same problem here... true for Mac OS X (very high CPU Load for "Wire Helper"), iPhone and iOS (App crashes). 

I like to chat with a default of 1h message lifetime. After some messages (50+ over the day) iPhone and IOS Apps starts to crash (can be reopened). If you carry on messaging... you have to reopen the App two or more times. 

(not the best) workaround: I delete the content of the chat... App acts normal for a bunch of time (half a day)... then same problem occurs again (after continuing using 1h messages).

**Comment by gregor** [comment]
Thanks. As stated we have fixed this internally already and hope to get this out to you all soon.

**Comment by gregor** [comment]
The release was pushed to production this morning. Please quite and restart your desktop app and ensure that you are running webapp version 2018.08.06.0803 which contains the fix.

**Comment by TiGR** [comment]
@gregor please, reopen this issue, since it is not fixed.

If there are no ephemeral messages in currently open chat in wire app, wire-desktop takes ~0.3% CPU. But if there is at least one message, that would last, say, 1 day, CPU usage is constantly above 20%. And the more ephemeral messages there are, the bigger it gets. For intance, with 20 messages CPU isage is around 35%.

Idle chat app window should never take that much CPU. This is really bad for battery life.

Using Wire for Web 2018.08.06.0803

**Comment by TiGR** [comment]
BTW, just tested the same in Signal desktop. There are animations, but most of the time signal-desktop uses around 0% CPU, even with multiple ephemeral messages lasting 1 day. It gets around ~3% with ten messages with 1 minute limit.
