### ISSUE TITLE
Wire crashes when trying to share screen

### ISSUE THREAD

**Issue by joels341** [wireapp/wire-desktop#2469]
Wire version: 3.9.2928
Operating system: Windows 10 Home (1803)
Which antivirus software do you have installed: AVG

What steps will reproduce the problem?

1.  Click share screen button during a call
2.  Wire crashes

What is the expected result?

Screen should be shared.

What is the actual result?

Wire crashes to desktop.

**Comment by ffflorian** [comment]
@joels341 this should be fixed by now. Can you try if it works for you now?

**Comment by kennaas** [comment]
Hi. I am having the same issue, and it is not fixed for me. Does anyone know a solution?

**Comment by ffflorian** [comment]
@kennaas which version of Wire Desktop and which operating system are you using?

**Comment by kennaas** [comment]
Wire version: 3.9.2928

OS: Windows 10

**Comment by ffflorian** [comment]
@kennaas this should be fixed with our latest version. Can you please check?

**Comment by ffflorian** [comment]
Closing this due to inactivity.
