### ISSUE TITLE
There is no badge over tray icon anymore

### ISSUE THREAD

**Issue by mohammadrafigh** [wireapp/wire-desktop#263]
I see commits that changed the badge to red in recent release, but it seems it's not affected in Linux (Gnome on Ubuntu). actually the blue badge is gone but when receiving new messages the red badge wouldn't appear on tray.

**Comment by gregor** [comment]
Good point. I see where my changes go wrong. We will fix it.

**Comment by gregor** [comment]
The fix was merged. It will be part of the next build - or can build from master yourself at this time.

**Comment by mohammadrafigh** [comment]
great thanks

**Comment by smares** [comment]
Umm, I still don't have a badge for unread messages with Ubuntu 16.10 (coming from 16.04). Only the regular Wire icon is displayed in the tray.
