### ISSUE TITLE
Application have icon inconsistencies accross Linux desktops

### ISSUE THREAD

**Issue by Porkepix** [wireapp/wire-desktop#3170]
Wire version: 3.10.2904
Wire for web version: 2019.10.16.1539
Operating system: ArchLinux - no version (rolling release)
Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Just run the application

What is the expected result?

Have the correct Wire icon everywhere

What is the actual result?

Some places have an icon which isn't the Wire icon.
For example in the PulseAudio volume control, Wire's icon actually is Chromium's icon (see screenshot below). Currently on a KDE/Plasma desktop, application's icon is the correct one in the taskbar and in the notification tray, but is X.org's icon in window's titlebar and in the task switcher (see screenshot for the titlebar; I can't take one for the task switcher).

If I remember correctly, the icon was the correct one for Gnome. I can check other desktops/window managers if needed.

Please provide any additional information below. Attach a screenshot if possible.
PulseAudio Volume Control:

![Screenshot_20191029_212612](https://user-images.githubusercontent.com/709500/67826430-bc3e9080-facc-11e9-9293-5267f3d7958e.png)

Wire's window titlebar:
![Screenshot_20191030_041845](https://user-images.githubusercontent.com/709500/67826463-d5dfd800-facc-11e9-9f47-ecc61fe727c2.png)

**Comment by ffflorian** [comment]
Hi @Porkepix, this is probably an Electron issue as we are already setting the icon and it is correctly set in Gnome and other desktop managers.

**Comment by ffflorian** [comment]
After some more investigation I found out that we were actually not setting the correct icon in some cases. Apologies! This will be fixed in the next release.

**Comment by ffflorian** [comment]
@Porkepix this should be fixed now.

**Comment by Porkepix** [comment]
@ffflorian This is actually only particially fixed: the titlebar icon is indeed fixed, however the icon inPulseAudio Volume Control still shows Chromium one.

Additionally, a little bit different but still linked issue I think (I can open another one if needed): if user hover the icon in the notification tray, it shows up as `electron6` rather than Wire.

**Comment by ffflorian** [comment]
Since you are using the Arch Linux version (which is not built by Wire), I unfortunately can't help further. Maybe @maximbaz knows more about this.

**Comment by Porkepix** [comment]
@ffflorian Yes, but I don't think there are any modifications compared to what's available here, as visible here, on the instructions to build the package: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/wire-desktop

ArchLinux doesn't do much patching as other distributions does, so it basically just looks like a `yarn build` targeting Linux, nothing else.

**Comment by ffflorian** [comment]
> so it basically just looks like a yarn build targeting Linux, nothing else.

In general yes, but it uses a [patched version of Electron](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/electron6) for example. It's possible that the difference lies there. Anyway, let's see what @maximbaz has to say since he maintains the Arch version :)

**Comment by maximbaz** [comment]
I think the difference must be coming from the way we launch the app, we don't build a big binary that contains bundled electron but we use a system electron and run `/usr/bin/electron6 /usr/lib/wire-desktop/`, it is possible that in this case the icon (and hover message) both come from `electron6` binary itself... 🤔 

I'll try to search around, ideas are welcome too, feel free to reach me by email as to not annoy wire devs with irrelevant notifications 😉

**Comment by ffflorian** [comment]
Thanks @maximbaz! :+1:

I will close this for now. Feel free to ping me if this turns out to be a Wire problem and I'll re-open.
