### ISSUE TITLE
wire for windows 3.17 goes to 'create account or login' screen randomly- losing message history on same device

### ISSUE THREAD

**Issue by macexpertsusa** [wireapp/wire-desktop#3901]
Greetings,

Using Wire for Windows 3.17 (since this update)

Wire has been repeatedly going to the 'create account or login'  (after already being logged into 3 accounts)
Upon seeing 'create account or login' If you selected Quit and relaunched Wire all was well it would log you back in to your accounts as normal  but this was happening several times a day since this last update so the last time I saw the 'create account or login' i noticed the X on top right so thought this might be a layover/splash screen (icons for 3 accounts were on left) and clicked it to see how Wire would respond and wire simply deleted one of the accounts! (If you right click an account on the left side and 'remove' it will verify you wish to remove the account but with this splash screen 'create account or login' it merely deleted the account).  

So I added the account back, entered details/password and Wire now thinks this is a new Wire session/DEVICE and says I'm using Wire for the first time on this device (this is the primary device for that account so all history is now gone).

Wire still see's the original session/DEVICE from 2019 in the device log but I cannot figure out anyway to get back to that session and my history from Wire for Windows. I have removed and added the account using the email and username in case this might trigger Wire to realize that this is NOT a new device but that has not met with success.

Other contacts on Wire have told me they are getting cannot connect to server problems. I have not seen this error but being put to 'create account or login' may be because of difficulty connecting to the wire servers - I am not sure.

I suspect this will happen to many other users due to whatever is causing Wire to go to the 'create account or login' page after you were already logged in. Merely clicking X on top right will remove that account without warning prompt and would result in history loss presumably for most users as well!

In the meantime does anyone know how I might trigger Wire for Windows to NOT think I'm on a new device and re-open the specific fingerprint in the devices that are listed? It is the same Windows system and primary installation point/useage point for Wire for Windows.

All the best!

**Comment by tomkap** [comment]
The same for Linux client

**Comment by jussihuotari** [comment]
Same on Mac. When waking my Mac from sleep state, the Wire client asks to log in again. If I quit the app and restart it, the client opens nicely and shows my chat history (i.e. I'm logged in).

I'd suggest changing the issue title to something like `Wire v3.17 goes to 'create account or login' screen even when acocunt data is present`.

Speculation: It seems like the issue started appearing since the SSO update in https://github.com/wireapp/wire-webapp/releases/tag/2020-04-29-production.0

**Comment by macexpertsusa** [comment]
I caught it in the act this time I believe. Instead of returning I was actually using Wire typing
I Started getting an orange bar across the top of Wire
Then it  updated a lagging message that was outgoing
Then it took me to the login window
I quit and restarted and now it demands a login to the account I was just using!!!!!!!!!
This is my primary account so presumably I will lose all my chat messages due to this glitch on this account as well. 
I believe there is a server issue or feed issue to the server - the client loses contact and bugs out.
This time there was no X on top on that splash screen to login or create account so the risk of deletion of the account unintentionally wasn't there. Does anyone know if this was a change in the past week or so? Should I try to login again or am I apt to lose my entire message history again?


Other contacts are losing their message history getting hit with the login screen. One was using a Mac also.
My secondary account still shows the original session in DEVICES even though I'm on the same system it thinks I'm on a new one - how that glitch is working and how to reverse it? We need a specific way to login to that DEVICE session so our history is restored. 

We are 6 or 7 days into this report and I'm sure thousands upon thousands of users are being affected.  We need help on this one ASAP please.

**Comment by tokariu** [comment]
same here. happens every day a few times.
I never entered my account details after this happens I just restart the app and I'm logged in again.
I know it's likely that when I enter my account details I will lose my history once again (...not that it really matters anymore after I lost my history so many times in the past due to Wire bugs.. sigh).


Win10
Version 3.17.3598
Wire für Web Version 2020.05.20.1224

**Comment by GeckoEidechse** [comment]
Same here on Linux. I had the client open throughout the day worked just fine at first. After a few hours of it being minimised in the background I opened it again and was greeted with the welcome login screen. I had two accounts active and both seem to have been removed.

* OS: Ubuntu 20.04 LTS
* Wire Snap, Version 3.17.2924

**Comment by macexpertsusa** [comment]
> Same here on Linux. I had the client open throughout the day worked just fine at first. After a few hours of it being minimised in the background I opened it again and was greeted with the welcome login screen. I had two accounts active and both seem to have been removed.
> 
> Both restarting Wire and restarting my device did not fix the issue.
> 
> * OS: Ubuntu 20.04 LTS
> * Wire Snap, Version 3.17.2924
> 
> **EDIT:** I tried logging back in and after successfully entering my credentials, my messages etc. were all still there. Further my device id and key fingerprint stayed the same. Same for the second account after entering its own set of credentials.
Thanks for the info everyone. 
Had another contact have the same issue but much later than I did - this person lost all message history and was using just one account. This was a Mac client.

I went ahead and used my credentials on the primary account and it did not decide I was on a new device and my messages were intact. 

No such luck on the original issue/secondary account which lost all message data. Does anyone know how to trigger wire to use the original fingerprint and device ID so I can get to my old message history on the 2nd account? I tried logging in and out with username and email thinking one or the other might trigger it. The original fingerprint/ID still exist as a device I'm just unable to invoke them on the same device!   

All the best

**Comment by pepper-jk** [comment]
Could not read all messages here yet, but I have a similar issue on Arch Linux with Wire 3.18.2925.

It started with wire sending my to the login screen, when my ethernet reconnected (after suspend to RAM). But a restart of the app solved it and I was back into my account. Today was the first time that this did not help.

Anyone got a workaround yet?

**Comment by jussihuotari** [comment]
Update: I haven't experienced this issue on my Mac after I upgraded Wire to v3.18. I don't know if it is *because* of the new version or just by coincidence 🤞

**Comment by mythsunwind** [comment]
Sorry, that this took so long to tackle. We deployed a fix for it with 3.18 and also the ability to get debugging logs from the menu bar. We know that there is still can be such logout events which are usually triggered by wifi or suspend mode, but they should not result in any history loss anymore. If you still experience history loss, please reopen.

**Comment by pepper-jk** [comment]
There is another issue #3790 on this, which is not fixed yet.
