### ISSUE TITLE
Cannot find module '../screen' - JavaScript error every time Wire is opened

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-desktop#467]
![wire_error](https://cloud.githubusercontent.com/assets/22968420/23316955/d704dff8-facc-11e6-8702-7ead1409cfec.png)

This happens every time when bringing Wire window from tray, i.e. first I close the window with X to minimize it to tray, then I click on its icon in the launcher to bring it back, and there I get the error.

If I click on the tray icon > Open Wire, there's no error.

**Comment by gregor** [comment]
Can repro that...

**Comment by anatoli26** [comment]
@gregor, sorry, do you mean "can" or "can't"?

**Comment by gregor** [comment]
Can - we opened an issue internally and will take a look.

**Comment by lipis** [comment]
Seems like it was introduced with Electron 1.6 :/

**Comment by anatoli26** [comment]
Are there beta versions available for each platform before the releases are published? I'd like to test them and report back to help release Wire to the mainstream users free of highly visible bugs like this one.

**Comment by lipis** [comment]
@anatoli26 The best option is to build the master branch, as we don't have publicly available pre-release binaries.

**Comment by anatoli26** [comment]
Yeah, I though about that, but an issue could be added in the latest build, untested by the community testers. Also, it's difficult to be building the packages frequently (like every day or 2) for the community testers and this way some parts of the new functionality may not receive enough usage. Also, the iOS version can't be tested by the community this way.

Would it be reasonable to introduce some staging period for the release builds and announce them as such? And enroll testers for beta versions of the iOS builds?

**Comment by lipis** [comment]
@anatoli26 We will start using the [releases](https://github.com/wireapp/wire-desktop/releases) section more and possible link there to the pre-release binaries. Would that work?

**Comment by anatoli26** [comment]
Sure, it would be great! If we (the Wire community enthusiasts) could somehow receive the news that a new pre-release binary is available, that would be enough.

It would be useful to have some channel for this type of single and bi-directional communications, in this case for the community developers & testers (like what we have discussed in another issue where you mentioned Medium).

**Comment by JR1994** [comment]
I can reproduce this issue on my laptop. Here is my set up
OS: Debian Sid
DE: Gnome Shell

When I first launch Wire it loads with no issue. If I close then launch from the Gnome System Tray then the error does not show up If I launch the app from the panel or after searching for the app that error pops up. If I close the app on the Tray then I can launch from the panel with no issue. It looks like if the app is running on background that to relaunch it from the panel causes an error.

**Comment by gregor** [comment]
Thanks for reporting. This is a known issue with Electron 1.6.1 found in 2.11.2722. We downgraded to the older version 1.4.15 of Electron again and released 2.12.2729.

**Comment by Reqas** [comment]
I can reproduce on Ubuntu Gnome 16.04 LTS. The error does not pop up if Wire is launched manually it seems, but it does if Wire > "Launch Wire on Startup" is selected. 

Can it be related to https://github.com/electron/electron/issues/4733 ?

**Comment by lipis** [comment]
I think we can close this issue now..

**Comment by anatoli26** [comment]
Closing it as it looks like it's fixed in the 2.12.2729

**Comment by gregor** [comment]
The issue still persists in electron 1.6.2. We are tracking it - but for now version starting from 2.13.2730 will again exhibit this problem.

**Comment by anatoli26** [comment]
Just installed Wire from PPA on Linux, seeing it again. Is there absolutely no fix for in the latest electron? Is this happening in other apps to? Could you please provide a link to the corresponding bug in electron?

**Comment by gregor** [comment]
https://github.com/electron/electron/issues/8862 Thanks for reporting. Did not keep track of this on Linux side before the release. Electron issue has not yet been fixed but there is a workaround that we might implement for the next release.

**Comment by gregor** [comment]
Renaming the issue for easier discoverability.

**Comment by aquatooth** [comment]
is this now fixed? it is a little unclear reading this thread! please close if yes!

**Comment by gregor** [comment]
Yes it was fixed with https://github.com/wireapp/wire-desktop/pull/593
